const TASKS_LOG_GROUP = "@trebired/tasks";

const DEFAULT_TASK_GLOBAL_CONCURRENCY = 4;
const DEFAULT_TASK_POLL_INTERVAL_MS = 1_000;
const DEFAULT_TASK_HEARTBEAT_MS = 10_000;
const DEFAULT_TASK_LEASE_MS = 30_000;
const DEFAULT_TASK_STOP_TIMEOUT_MS = 30_000;
const DEFAULT_TASK_STALE_SCAN_INTERVAL_MS = 15_000;
const DEFAULT_TASK_STALE_SCAN_LIMIT = 100;
const DEFAULT_TASK_MAX_ATTEMPTS = 1;

const DEFAULT_TASK_BACKOFF_MIN_DELAY_MS = 1_000;
const DEFAULT_TASK_BACKOFF_MAX_DELAY_MS = 60_000;
const DEFAULT_TASK_BACKOFF_FACTOR = 2;
const DEFAULT_TASK_BACKOFF_JITTER = 0.1;

export {
  DEFAULT_TASK_BACKOFF_FACTOR,
  DEFAULT_TASK_BACKOFF_JITTER,
  DEFAULT_TASK_BACKOFF_MAX_DELAY_MS,
  DEFAULT_TASK_BACKOFF_MIN_DELAY_MS,
  DEFAULT_TASK_GLOBAL_CONCURRENCY,
  DEFAULT_TASK_HEARTBEAT_MS,
  DEFAULT_TASK_LEASE_MS,
  DEFAULT_TASK_MAX_ATTEMPTS,
  DEFAULT_TASK_POLL_INTERVAL_MS,
  DEFAULT_TASK_STALE_SCAN_INTERVAL_MS,
  DEFAULT_TASK_STALE_SCAN_LIMIT,
  DEFAULT_TASK_STOP_TIMEOUT_MS,
  TASKS_LOG_GROUP,
};
